# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov pytest-cov mypy pylint flake8 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 fll test --ignore=E731 --max-line-length=120
    - name: Lint with PyLint
      run: |
        pylint --fail-under=10.0 fll
    - name: Type testing
      run: |
        mypy fll
    - name: Test with pytest
      run: |
        pytest -v --cov
        codecov
    - name: Doctest
      run: |
        cd docs
        make doctest
